# Generated by Django 2.0.3 on 2018-03-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niños', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'verbose_name': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('actividades', models.ManyToManyField(to='clubes.Actividades')),
            ],
            options={
                'verbose_name_plural': 'Casas',
                'verbose_name': 'Casa',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ninos_cuenta', models.IntegerField(verbose_name='Total de niños')),
                ('ninos', models.ManyToManyField(to='niños.Niño', verbose_name='Niños')),
            ],
            options={
                'verbose_name_plural': 'Clubes',
                'verbose_name': 'Club',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Actividades')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Casas')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionElementosClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('confifuracion_actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionActividades')),
                ('confifuracion_casas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionCasas')),
                ('confifuracion_elemento_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionElementosClave')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('casas', models.ManyToManyField(to='clubes.Casas')),
            ],
            options={
                'verbose_name_plural': 'Elementos clave',
                'verbose_name': 'Elemento clave',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('edad_minima', models.IntegerField(max_length=2, verbose_name='Edad inicial')),
                ('edad_maxima', models.IntegerField(max_length=2, verbose_name='Edad final')),
                ('objetivo', models.TextField()),
                ('tipo', models.CharField(choices=[('INF', 'Informativo'), ('INT', 'Interactivo')], max_length=3)),
                ('elementos_clave', models.ManyToManyField(to='clubes.ElementoClave')),
            ],
        ),
        migrations.AddField(
            model_name='configuracionelementosclave',
            name='elemento_clave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ElementoClave'),
        ),
    ]
