# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ninos_cuenta', models.IntegerField(verbose_name=b'Total de ni\xc3\xb1os')),
                ('ninos', models.ManyToManyField(to='ninos.Nino', verbose_name=b'Ni\xc3\xb1os')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionElementosClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Elemento clave',
                'verbose_name_plural': 'Elementos clave',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('edad_minima', models.IntegerField(verbose_name=b'Edad inicial')),
                ('edad_maxima', models.IntegerField(verbose_name=b'Edad final')),
                ('objetivo', models.TextField()),
                ('tipo', models.CharField(choices=[(b'INF', b'Informativo'), (b'INT', b'Interactivo')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='elementoclave',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Programa'),
        ),
        migrations.AddField(
            model_name='configuracionprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Programa'),
        ),
        migrations.AddField(
            model_name='configuracionelementosclave',
            name='configuracion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionPrograma'),
        ),
        migrations.AddField(
            model_name='configuracionelementosclave',
            name='elemento_clave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ElementoClave'),
        ),
        migrations.AddField(
            model_name='configuracioncasas',
            name='configuracion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionPrograma'),
        ),
        migrations.AddField(
            model_name='configuracionactividades',
            name='configuracion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionPrograma'),
        ),
        migrations.AddField(
            model_name='casa',
            name='elemento_clave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.ElementoClave'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.Casa'),
        ),
    ]
