# Generated by Django 2.0.3 on 2018-03-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_auto_20180320_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionElementosClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracionprograma',
            name='configuracion_actividades',
        ),
        migrations.RemoveField(
            model_name='configuracionprograma',
            name='configuracion_casas',
        ),
        migrations.RemoveField(
            model_name='configuracionprograma',
            name='configuracion_elementos_clave',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='elementos_clave',
        ),
        migrations.AddField(
            model_name='configuracionprograma',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubes.Programa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementoclave',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubes.Programa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionelementosclave',
            name='configuracion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionPrograma'),
        ),
        migrations.AddField(
            model_name='configuracionelementosclave',
            name='elemento_clave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ElementoClave'),
        ),
        migrations.AddField(
            model_name='configuracioncasas',
            name='configuracion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionPrograma'),
        ),
        migrations.AddField(
            model_name='configuracionactividades',
            name='configuracion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ConfiguracionPrograma'),
        ),
    ]
