# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name=b'C\xc3\xb3digo')),
                ('edad', models.IntegerField()),
                ('es_apadrinado', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
