# Generated by Django 2.0.3 on 2018-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niños', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niño',
            name='padrino',
        ),
        migrations.AddField(
            model_name='niño',
            name='es_apadrinado',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Padrino',
        ),
    ]
