# Generated by Django 2.0.3 on 2018-03-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('edad', models.IntegerField(max_length=2)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='niño',
            name='padrino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='niños.Padrino'),
        ),
    ]
