# Generated by Django 2.0.3 on 2018-03-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_auto_20180320_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
        migrations.RemoveField(
            model_name='casas',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='configuracionactividades',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='configuracioncasas',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='configuracionelementosclave',
            name='elemento_clave',
        ),
        migrations.RemoveField(
            model_name='configuracionprograma',
            name='confifuracion_actividades',
        ),
        migrations.RemoveField(
            model_name='configuracionprograma',
            name='confifuracion_casas',
        ),
        migrations.RemoveField(
            model_name='configuracionprograma',
            name='confifuracion_elemento_clave',
        ),
        migrations.RemoveField(
            model_name='elementoclave',
            name='casas',
        ),
        migrations.AddField(
            model_name='configuracionprograma',
            name='configuracion_elementos_clave',
            field=models.ManyToManyField(to='clubes.ElementoClave'),
        ),
        migrations.DeleteModel(
            name='Actividades',
        ),
        migrations.DeleteModel(
            name='Casas',
        ),
        migrations.DeleteModel(
            name='ConfiguracionActividades',
        ),
        migrations.DeleteModel(
            name='ConfiguracionCasas',
        ),
        migrations.DeleteModel(
            name='ConfiguracionElementosClave',
        ),
        migrations.AddField(
            model_name='casa',
            name='elemento_clave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.ElementoClave'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.Casa'),
        ),
        migrations.AddField(
            model_name='configuracionprograma',
            name='configuracion_actividades',
            field=models.ManyToManyField(to='clubes.Actividad'),
        ),
        migrations.AddField(
            model_name='configuracionprograma',
            name='configuracion_casas',
            field=models.ManyToManyField(to='clubes.Casa'),
        ),
    ]
